% --- regenerative braking simulation (boost converter model) ---
clear; clc; close all;

%Note:






%% -------------------------- INPUTS USER CAN CHANGE -------------------------------------------------------------
%-----------------------------------------------------------------------------------------------------------------
%-----------------------------------------------------------------------------------------------------------------

mass = 2400;                              % mass of train (kg)
wheelradius = 0.1;                        % radius (meters)
gearratio = 10;                           % gear ratio
crr = 0.004;


% current limit - prevents infinite power at low voltages
max_current_limit = 150;                  % Amps


% BRAKING
initial_speed = 4.17;                     % initial speed (15 km/h in m/s)
decel_rate = 0.4;                         % braking of 0.6 m/s^2


% ACCELERATION
target_speed_kmh = 15;                    % target speed to reach when accelerating using energy recovered
acceleration = 0.4;


% MOTOR CONSTANTS
nominal_voltage = 48;
nominal_rpm = 4000;
pair_poles = 4;

B = 1.0;                                  % Tesla (max magnetic flux)
k_h = 0.015;                              % W/(Hz·T^n·kg)
k_e = 0.0003;                             % W/(Hz^2·T^2·kg)
n   = 1.6;
m_fe = 7.6*0.35;                               % kg of stator iron per motor




% SUPERCAPACITOR CONSTANTS
c = 165;                                  % capacitance (farads)
cap_pre_charge = 1;                      % pre-charge voltage (volts)








%% ------------------- PHASE 1 - VOLTAGE RISE WHILE BRAKING ----------------------------------


% 1. system constants
nominal_w = nominal_rpm*(2*pi/60);
kv = nominal_rpm/nominal_voltage;         % motor constant (volts/(rad/s))
kt = 8.27/kv;
ke = kt * (3/2);                                  % torque constant (nm/a)
r_circuit = (9.6e-3)/2;                          % internal resistance (wires + cap esr)
efficiency = 0.85;                        % controller boost efficiency (85%)

cap_voltage = cap_pre_charge;


% compute current output when braking
f_braking = mass * decel_rate;
t_wheels = f_braking * wheelradius;
t_motor = t_wheels/gearratio;
t_per_motor = t_motor/2;
brakingcurrent = t_per_motor/kt;



% simulation setup
dt = 0.01;           % time step (seconds)
time = 0;
results = [];        % array to store data for plotting

% simulation loop (run until stopped)
while initial_speed > 0.05
    
    % --- mechanical physics ---
    % calculate rpm
    wheelrpm = (initial_speed * 60) / (2 * pi * wheelradius);
    motorrpm = wheelrpm * gearratio;
    motor_w = motorrpm * (2*pi/60);

    
    % Steinmetz iron losses per motor
    f_e = pair_poles * motor_w / (2*pi);                    % eletrical frequency
    p_h = k_h * f_e * B^n * m_fe;
    p_e = k_e * f_e^2 * B^2 * m_fe;

    p_fe_total = 2 * (p_h + p_e);

    
    % calculate motor back emf
    v_motor = motor_w * ke - r_circuit*brakingcurrent;     
    
    % calculate braking torque & force
    % torque = kt * current * gearratio
    torque_total = 2 * (kt * brakingcurrent) * gearratio; % 2 motors
    braking_force = torque_total / wheelradius;
    
    % decelerate the train (f = ma -> a = f/m)
    decel = braking_force / mass;
    initial_speed = initial_speed - (decel * dt);
    
    % --- electrical physics (the boost controller) ---
    % power generated by motor = voltage * current
    p_motor = v_motor * brakingcurrent * 2 - p_fe_total; % 2 motors
    
    % power delivered to capacitor = motor power * efficiency
    p_charging = p_motor * efficiency;
    
    % calculate current going into the capacitor
    % p = v * i  ->  i = p / v
    i_cap = p_charging / cap_voltage;
    
    % update capacitor voltage
    % dV = (I * dt) / C
    cap_voltage = cap_voltage + (i_cap * dt / c);

    if cap_voltage > 48
        fprintf('!!! REACHED SUPERCAPACITOR MAXIMUM VOLTAGE\nDECREASE SUPERCAPACITOR PRE-CHARGE AND TRY AGAIN\n ');
        return;
    end
    
    % --- data logging ---
    time = time + dt;
    % store: [time, speed, motorVoltage, capVoltage, capCurrent]
    results = [results; time, initial_speed, v_motor, cap_voltage, i_cap];
end






%% ---------------------- PHASE 2 - COMPUTE DISTANCE TRAVELLED WITH RECOVERED ENERGY ------------------------

fprintf('Starting phase 2 - travel with energy recovered\n\n');

% calculate current input to motor while accelerating (NEGLETING INCLINED PLANE)

%when accelerating
total_traction_force = (mass * acceleration) + (mass * 9.81 * crr);%assuming plane
torque_wheels = total_traction_force * wheelradius;
torque_motor = torque_wheels/(gearratio * 0.85);
torque_per_motor = torque_motor/2;
current_accel_per_motor = torque_per_motor/kt;

fprintf('Current during Acceleration per motor: %.2f Amps\n', current_accel_per_motor);


% when cruising (a=0)
f_friction = mass * 9.81 * crr;%assuming plane
t_wheel_cruise = f_friction * wheelradius;
t_motor_cruise = t_wheel_cruise /(gearratio*0.85);
t_per_motor_cruise = t_motor_cruise / 2;
current_cruise_per_motor = t_per_motor_cruise / kt;

fprintf('Current during Cruising per motor: %.2f Amps\n', current_cruise_per_motor);



% phase 2 variables
target_speed = target_speed_kmh/3.6;
velocity_drive = 0;
distance_total = 0;
distance_at_empty = 0;
has_reached_limit = false;
time_drive = 0;
results_drive = [];



% driving loop
while true

    % 1. CHECK ENERGY STATUS
    if cap_voltage > cap_pre_charge
        has_energy = true;
    else
        has_energy = false;
    end

    % 2. DETERMINE DESIRED CURRENT (Target)
    if has_energy == true
        if velocity_drive < target_speed
            current_target = current_accel_per_motor;
            mode = 1;       % accel
        else
            current_target = current_cruise_per_motor;
            mode = 2;       % cruise
        end
    else
        current_target = 0;
        mode = 3;           % coast
    end


    % 3. *** NEW LOGIC: CHECK CURRENT LIMIT & UPDATE CAPACITOR ***
    % We do this BEFORE calculating force, so we know if we actually have power.
    
    current_real = current_target; % Default assumption
    
    wheelrpm_drive = (velocity_drive * 60) / (2 * pi * wheelradius);
    motor_w_drive = (wheelrpm_drive * gearratio) * (2*pi/60);
    v_bemf = motor_w_drive * ke - r_circuit*current_real;
    
    if has_energy
        % Calculate Losses
        f_e = pair_poles * motor_w_drive / (2*pi);
        p_fe_total = 2 * (k_h * f_e * B^n * m_fe + k_e * f_e^2 * B^2 * m_fe);

        % Power needed from capacitor
        p_mech_elec = (v_bemf * current_real) * 2;
        p_total_load = p_mech_elec + p_fe_total;
        p_needed_from_cap = p_total_load / 0.85;
        
        % Current needed from capacitor
        i_cap_needed = p_needed_from_cap / cap_voltage;
        
        % --- THE LIMITER ---
        if i_cap_needed > max_current_limit
            % We cannot provide this much current! Clamp it.
            i_cap_out = max_current_limit;
            
            % Recalculate what the motor actually gets
            p_available = i_cap_out * cap_voltage * 0.85;
            p_for_torque = p_available - p_fe_total;
            
            if v_bemf > 0.1
                current_real = p_for_torque / (2 * v_bemf);
            else
                current_real = max_current_limit; % Stall torque limit
            end
            
            % prevent negative current logic errors
            if current_real < 0, current_real = 0; end
            
        else
            % We are fine, supply requested current
            i_cap_out = i_cap_needed;
            current_real = current_target;
        end
        
        % Discharge Capacitor
        dV = (i_cap_out * dt) / c;
        cap_voltage = cap_voltage - dV;

        if cap_voltage <= cap_pre_charge && ~has_reached_limit
            distance_at_empty = distance_total;
            has_reached_limit = true;
        end
    else
        current_real = 0;
    end

    % 4. CALCULATE FORCE WITH REAL CURRENT
    if mode == 3
        force_push = 0;
    else
        torque_produced = 2 * (current_real * kt) * gearratio * 0.85;
        force_push = torque_produced / wheelradius;
    end

    % 5. MECHANICAL PHYSICS
    crr_force = mass*9.81*crr;
    f_mech = 0.002*mass*9.81;
    force_resistive = crr_force + f_mech;

    force_net = force_push - force_resistive;
    accel_real = force_net / mass;

    velocity_drive = velocity_drive + (accel_real * dt);

    % Speed limiter 
    if velocity_drive > target_speed && mode ~= 3
        velocity_drive = target_speed;
    end

    % Stopping condition
    if velocity_drive <= 0.05 && mode == 3
        break;
    end

    distance_total = distance_total + (velocity_drive * dt);
    time_drive = time_drive + dt;
    
    % Store real current for plotting
    results_drive = [results_drive; time_drive, velocity_drive, cap_voltage, distance_total, mode, v_bemf, current_real];
end

    

















%% ---------------------------------- PLOTS AND RESULTS -------------------------------------

figure('Name', 'Regen Braking Analysis');

% plot 1: voltages (the proof of boost)
subplot(2,1,1);
plot(results(:,1), results(:,3), 'r--', 'LineWidth', 2); hold on;
plot(results(:,1), results(:,4), 'g', 'LineWidth', 2);
title('The Boost Effect: Charging when Motor Voltage is Low');
legend('Motor Back-EMF (Dropping)', 'Capacitor Voltage (Rising)');
ylabel('Voltage (V)'); xlabel('Time (s)');
grid on;

% plot 2: speed and current
subplot(2,1,2);
yyaxis left
plot(results(:,1), results(:,2), 'b', 'LineWidth', 2);
ylabel('Train Speed (m/s)');
yyaxis right
plot(results(:,1), results(:,5), 'k', 'LineWidth', 1);
ylabel('Current Into Capacitor (A)');
title('Train Speed vs Charging Current');
xlabel('Time (s)');
grid on;

% --- new figure: power & capacitor current ---
figure('Name', 'Power & Current Analysis');

% 1. calculate power vector for plotting
% power = motor voltage (col 3) * braking current * 2 motors
power_motor_vector = results(:,3) .* brakingcurrent .* 2;

% subplot 1: power generated by motors
subplot(2, 1, 1);
plot(results(:,1), power_motor_vector, 'm', 'LineWidth', 2);
title('Total Power Generated by Motors (Pre-Efficiency)');
xlabel('Time (s)');
ylabel('Power (Watts)');
grid on;
legend('P_{generated} = V_{emf} * I_{brake} * 2');

% subplot 2: current going into supercapacitor
subplot(2, 1, 2);
plot(results(:,1), results(:,5), 'k', 'LineWidth', 2);
title('Actual Current Entering Supercapacitor');
xlabel('Time (s)');
ylabel('Current (Amps)');
grid on;
legend('I_{cap} (Drops as Voltage Drops)');

% --- final results ---
% the 'end' keyword grabs the very last entry in the array
final_cap_voltage = results(end, 4);





figure('Name', 'Phase 2: Driving Range');

% Subplot 1: Speed
subplot(3,1,1);
plot(results_drive(:,4), results_drive(:,2), 'b', 'LineWidth', 2);
% Find the row index where Mode 3 starts
idx_coast = find(results_drive(:,5)==3, 1);

% Get the distance (Column 4) from that specific row
if ~isempty(idx_coast)
    xline(results_drive(idx_coast, 4), '--k', 'Power Cut');
end
title(['Total Distance: ' num2str(round(distance_total)) ' m']);
ylabel('Speed (m/s)'); xlabel('Distance (m)');
legend('Speed', 'Start of Coasting');
grid on;

% Subplot 2: Voltage Supply vs. Demand
subplot(3,1,2);

% Plot Capacitor Voltage (Column 3) - The Supply
plot(results_drive(:,4), results_drive(:,3), 'r', 'LineWidth', 2); hold on;

% Plot Motor Back-EMF (Column 6) - The Demand
plot(results_drive(:,4), results_drive(:,6), 'b--', 'LineWidth', 1.5);

% Plot the Limit Line
yline(cap_pre_charge, '--k', 'Empty Limit');

title('Voltage Convergence: Supply (Red) vs Demand (Blue)');
ylabel('Voltage (V)'); xlabel('Distance (m)');
legend('Capacitor Supply', 'Motor Back-EMF', 'Empty Limit');
grid on;


% Subplot 1: Speed vs Time
subplot(3,1,3);

% CHANGE 1: Use Column 1 (Time) for X-axis instead of Column 4 (Distance)
plot(results_drive(:,1), results_drive(:,2), 'b', 'LineWidth', 2);

% Find the row index where Mode 3 starts
idx_coast = find(results_drive(:,5)==3, 1);

% CHANGE 2: Get the TIME (Column 1) from that specific row for the vertical line
if ~isempty(idx_coast)
    xline(results_drive(idx_coast, 1), '--k', 'Power Cut');
end

% Optional: You might want to display Total Time in the title now
title(['Speed Profile over Time']);
ylabel('Speed (m/s)'); 
xlabel('Time (s)'); % CHANGE 3: Update label
legend('Speed', 'Start of Coasting');
grid on;




fprintf('--------------------------------------\n');
fprintf('Simulation Complete.\n');
fprintf('Pre-Charge Voltage:               %.2f V\n', results(1, 4));
fprintf('Final Voltage:                    %.2f V\n', final_cap_voltage);
fprintf('Voltage Rise:                     %.2f V\n', final_cap_voltage - results(1, 4));
fprintf('--------------------------------------\n\n');
fprintf('Range test:\n');
% Calculate Minutes and Seconds
mins = floor(time_drive / 60);
secs = rem(time_drive, 60);

fprintf('Distance travelled:              %.2f meters\n', distance_total);
if has_reached_limit
    fprintf('Distance until pre-charge limit: %.2f meters\n', distance_at_empty);
end
fprintf('Time elapsed:                    %d min %.0f sec\n', mins, secs);
fprintf('Final supercapacitor voltage:    %.2f V\n', cap_voltage);
fprintf('--------------------------------------\n\n');
